plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.android.kmp.library)
    alias(libs.plugins.kover)
}

/**
 * Turns manifest JSON into a Kotlin source for commonTest, because tests on the iOS simulator
 * cannot read files from the repo. Picks up the pipeline's `content/<chapter>/manifest.json` as
 * soon as they exist, so app CI holds every published manifest to the contract.
 */
abstract class GenerateManifestFixtures : DefaultTask() {
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val appFixtures: ConfigurableFileCollection

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val contentManifests: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        fun literal(text: String): String {
            // Short pieces keep each JVM string constant under its 64 KB limit; never split a surrogate pair.
            val pieces = mutableListOf<String>()
            var start = 0
            while (start < text.length) {
                var end = minOf(start + 8_000, text.length)
                if (end < text.length && text[end - 1].isHighSurrogate()) end--
                pieces += text.substring(start, end)
                start = end
            }
            return pieces.joinToString(" +\n            ") { piece ->
                val escaped = piece.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")
                    .replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
                "\"$escaped\""
            }.ifEmpty { "\"\"" }
        }
        fun entries(files: Set<File>, key: (File) -> String) = files.sortedBy(key).joinToString("") {
            "\n        \"${key(it)}\" to ${literal(it.readText())},"
        }

        val dir = outputDir.get().asFile.resolve("app/dheevara/core/fixtures").apply { deleteRecursively(); mkdirs() }
        dir.resolve("ManifestFixtures.kt").writeText(
            """
            |// Generated by :shared:core:generateManifestFixtures. Do not edit.
            |package app.dheevara.core.fixtures
            |
            |object ManifestFixtures {
            |    /** The app's own test fixtures, by chapter id. */
            |    val app: Map<String, String> = mapOf(${entries(appFixtures.files) { it.name.substringBefore('.') }}
            |    )
            |
            |    /** Every `content/<chapter>/manifest.json` the pipeline has published, by chapter id. */
            |    val content: Map<String, String> = mapOf(${entries(contentManifests.files) { it.parentFile.name }}
            |    )
            |}
            |""".trimMargin(),
        )
    }
}

val generateManifestFixtures = tasks.register<GenerateManifestFixtures>("generateManifestFixtures") {
    appFixtures.from(fileTree("src/commonTest/fixtures") { include("*.json") })
    contentManifests.from(fileTree(layout.settingsDirectory.dir("../../content")) { include("*/manifest.json") })
    outputDir = layout.buildDirectory.dir("generated/manifestFixtures")
}

// Android lint reads every test source directory but does not see the generator behind this one.
tasks.matching { it.name.contains("lint", ignoreCase = true) }.configureEach {
    dependsOn(generateManifestFixtures)
}

kotlin {
    jvmToolchain(21)

    jvm()
    android {
        namespace = "app.dheevara.core"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()
        withHostTest {}
    }
    iosArm64()
    iosSimulatorArm64()

    sourceSets {
        commonMain.dependencies {
            api(libs.kotlinx.datetime)
            implementation(libs.kotlinx.serialization.json)
        }
        commonTest {
            kotlin.srcDir(generateManifestFixtures.map { it.outputDir })
            dependencies {
                implementation(kotlin("test"))
            }
        }
    }
}

kover {
    reports {
        filters {
            excludes {
                // Code the serialization plugin writes, not ours.
                classes("*\$\$serializer")
            }
        }
        verify {
            rule("Line coverage of core") {
                minBound(90)
            }
        }
    }
}

tasks.named("check") {
    dependsOn("koverVerify")
}
