#!/usr/bin/env python3
"""Generate the app's icon set from the mockups' SVG <symbol id="i-*"> sprite.

Usage: python3 apps/dheevara/scripts/icons.py
Writes shared/ui/src/commonMain/kotlin/app/dheevara/ui/components/IconPaths.kt so the app draws
exactly the icons the mockups were reviewed with. Rects and circles become path strings.
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[3]
SOURCE = ROOT / "design/mockups/index.html"
OUT = ROOT / "apps/dheevara/shared/ui/src/commonMain/kotlin/app/dheevara/ui/components/IconPaths.kt"


def num(v):
    return f"{float(v):g}"


def rect(a):
    x, y, w, h = (float(a[k]) for k in ("x", "y", "width", "height"))
    r = min(float(a.get("rx", 0)), w / 2, h / 2)
    if r == 0:
        return f"M{num(x)} {num(y)}h{num(w)}v{num(h)}h{num(-w)}z"
    return (
        f"M{num(x + r)} {num(y)}h{num(w - 2 * r)}a{num(r)} {num(r)} 0 0 1 {num(r)} {num(r)}"
        f"v{num(h - 2 * r)}a{num(r)} {num(r)} 0 0 1 {num(-r)} {num(r)}h{num(-(w - 2 * r))}"
        f"a{num(r)} {num(r)} 0 0 1 {num(-r)} {num(-r)}v{num(-(h - 2 * r))}a{num(r)} {num(r)} 0 0 1 {num(r)} {num(-r)}z"
    )


def circle(a):
    cx, cy, r = (float(a[k]) for k in ("cx", "cy", "r"))
    return f"M{num(cx - r)} {num(cy)}a{num(r)} {num(r)} 0 1 0 {num(2 * r)} 0a{num(r)} {num(r)} 0 1 0 {num(-2 * r)} 0z"


def attrs(tag):
    return dict(re.findall(r'([\w-]+)="([^"]*)"', tag))


def main():
    html = SOURCE.read_text()
    entries = []
    for sid, body in re.findall(r'<symbol id="i-([a-z]+)"[^>]*>(.*?)</symbol>', html, re.S):
        paths = []
        for kind, tag in re.findall(r"<(path|rect|circle)\b([^>]*)/>", body):
            a = attrs(tag)
            paths.append(a["d"] if kind == "path" else rect(a) if kind == "rect" else circle(a))
        name = sid.capitalize()
        entries.append(f'    {name}(listOf({", ".join(repr(p).replace(chr(39), chr(34)) for p in paths)})),')
    OUT.write_text(
        "// Generated by apps/dheevara/scripts/icons.py from design/mockups/index.html. Do not edit.\n"
        "package app.dheevara.ui.components\n\n"
        "/** The mockups' icon set: SVG path data on a 24×24 grid, drawn with a 1.75 stroke. */\n"
        "enum class DIcon(val paths: List<String>) {\n" + "\n".join(entries) + "\n}\n"
    )
    print(f"{len(entries)} icons -> {OUT.relative_to(ROOT)}")


main()
