// pnpm canon:export — content/canon/export.json, the canon as the app and the web experiences read
// it (lineage explorer, reveal module): people with cited edges, and every claim with its verses.
// Derived only from committed canon files, so a test can check the committed export is current.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { loadCanon, CANON_DIR } from './index.mjs';

export function buildExport(canon = loadCanon()) {
  const ed = canon.editions.get('bori-ce');
  const claims = {};
  for (const [id, c] of [...canon.claims].sort(([a], [b]) => a.localeCompare(b, 'en', { numeric: true }))) {
    const { ref, passages } = canon.resolve(id);
    claims[id] = {
      ...ref,
      edition: ed.shownAs,
      statement: c.statement,
      status: c.status,
      ...(c.translation ? { translation: c.translation } : {}),
      ...(passages.length ? { verses: passages.map((p) => ({ id: p.id, devanagari: p.devanagari, iast: p.iast })) } : {}),
      ...(c.flags ? { flags: c.flags } : {}),
    };
  }
  return {
    note: 'Generated by pnpm canon:export from content/canon/. Verse text is BORI e-text quoted for citation; shipping it in the app needs BORI permission (docs/research/sources.md).',
    editions: [{ id: ed.id, shownAs: ed.shownAs, etext: ed.etext.description, notice: ed.etext.notice }],
    people: canon.people.map(({ id, names, revered, witness, edges }) => ({ id, names, revered, witness, edges })),
    claims,
  };
}

export const EXPORT_PATH = join(CANON_DIR, 'export.json');

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
  const data = buildExport();
  writeFileSync(EXPORT_PATH, JSON.stringify(data, null, 2) + '\n');
  console.log(`wrote content/canon/export.json: ${data.people.length} people, ${Object.keys(data.claims).length} claims`);
}
