// pnpm web:build — build the self-contained JS experiences in web/ from web/src/<name>.html.
// Each template may contain:
//   /*@include shared/reveal-sheet.js*/   the shared reveal module, inlined (DHE-27)
//   /*@data*/                              const DATA = {...}: the experience's script and every
//                                          claim it shows, resolved from the canon (rule 2)
// Outputs are committed; test/web.test.mjs fails if an output drifts from its source.
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadCanon } from '../src/canon/index.mjs';
import { buildExport } from '../src/canon/export.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SRC = join(ROOT, 'web', 'src');

/** A manifest-shaped claim (schema/chapter-manifest.schema.json $defs.claim) for one id. */
export function manifestClaim(canon, id) {
  const r = canon.resolve(id);
  if (!r) throw new Error(`${id} does not resolve in the canon (rule 2)`);
  const ed = canon.editions.get(r.claim.edition);
  const c = { book: r.ref.book, adhyaya: r.ref.adhyaya, ...(r.ref.verse ? { verse: r.ref.verse } : {}), ...(r.ref.verseEnd ? { verseEnd: r.ref.verseEnd } : {}), edition: ed.shownAs, status: r.claim.status };
  if (r.passages.length === 1) { c.devanagari = r.passages[0].devanagari; c.iast = r.passages[0].iast; }
  if (r.claim.translation) c.translation = { en: r.claim.translation.en };
  c.summary = { en: r.claim.statement };
  return c;
}

function claimIds(node, out = new Set()) {
  if (Array.isArray(node)) node.forEach((n) => claimIds(n, out));
  else if (node && typeof node === 'object') for (const [k, v] of Object.entries(node)) (k === 'claims' && Array.isArray(v) ? v.forEach((id) => out.add(id)) : claimIds(v, out));
  return out;
}

/** The DATA object for one experience. */
export function dataFor(name, canon) {
  if (name === 'lineage') {
    const exp = buildExport(canon);
    const used = claimIds(exp.people);
    return {
      editions: exp.editions.map(({ id, text, shownAs }) => ({ id, text, shownAs })),
      people: exp.people,
      claims: Object.fromEntries([...used].sort().map((id) => [id, manifestClaim(canon, id)])),
    };
  }
  const path = join(ROOT, 'content', 'web', `${name}.json`);
  if (!existsSync(path)) return null;
  const script = JSON.parse(readFileSync(path, 'utf8'));
  return { ...script, claims: Object.fromEntries([...claimIds(script)].sort().map((id) => [id, manifestClaim(canon, id)])) };
}

export function buildWeb(canon = loadCanon()) {
  const out = {};
  for (const file of readdirSync(SRC).filter((f) => f.endsWith('.html')).sort()) {
    const name = file.replace(/\.html$/, '');
    let html = readFileSync(join(SRC, file), 'utf8');
    html = html.replace(/\/\*@include ([\w./-]+)\*\//g, (_, rel) => readFileSync(join(ROOT, 'web', rel), 'utf8').trim());
    if (html.includes('/*@data*/')) {
      const data = dataFor(name, canon);
      if (!data) throw new Error(`${file} asks for data but content/web/${name}.json does not exist`);
      html = html.replace('/*@data*/', `const DATA = ${JSON.stringify(data)};`);
    }
    out[`${name}.html`] = html.replace('<!--@generated-->', `<!-- Generated by pnpm web:build from web/src/${file}; edit the source, not this file. -->`);
  }
  return out;
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
  for (const [name, html] of Object.entries(buildWeb())) {
    writeFileSync(join(ROOT, 'web', name), html);
    console.log(`wrote web/${name} (${(html.length / 1024).toFixed(1)} KB)`);
  }
}
